default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: datasets_api_dev

test:
  <<: *default
  database: datasets_api_test

production:
  <<: *default
  database: datasets_api_production
